services:
  postgres:
    image: postgres:16
    container_name: meteo-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: meteo-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "5050:80"

    depends_on:
      - postgres

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: meteo-streamlit
    restart: unless-stopped

    command: streamlit run dashboard/app.py --server.address=0.0.0.0 --server.port=8501

    ports:
      - "8501:8501"

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

    depends_on:
      - postgres


  airflow-db:
    image: postgres:16
    container_name: meteo-airflow-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:3.0.6
    container_name: meteo-airflow
    restart: unless-stopped
    depends_on:
      - airflow-db
    env_file:
      - .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    working_dir: /opt/airflow
    volumes:
      - .:/opt/airflow
    ports:
      - "8080:8080"
    command: standalone

volumes:
  postgres_data:
  airflow_db_data: