@startuml

hide circle
skinparam classAttributeIconSize 0

class CitiesExtractor {
    - file: str
    + extactor(): DataFrame
    + save_to_bronze(data: DataFrame)
}

class WeatherExtractor {
    - url: str
    - timeout: int
    + extractor(): list
    + save_raw_data(data: list)
    + parse_data_raw(data: list): DataFrame
    + save_to_bronze(data: DataFrame)
}

class DataCleaner {
    + clean_weather(data: DataFrame): DataFrame
    + save_to_silver(data: DataFrame)
}

class DataValidator {
    + validate_cities(data: DataFrame): bool
    + validate_weather(data: DataFrame): bool
    + check_validate_values(data: DataFrame): dict
}

class FeatureEngineer {
    + create_features(data: DataFrame): DataFrame
}

class RiskCalculator {
    + calculate_score(data: DataFrame): DataFrame
}

class Database {
    - user: str
    - password: str
    - database: str
    - host: str
    - port: str
    - url: str
    - engine: Engine
}

class DatabaseLoader {
    - database: Database
    + load_cities(data: DataFrame)
    + load_weather(data: DataFrame)
    + load_risks(data: DataFrame)
}

WeatherExtractor ..> CitiesExtractor : uses
DataCleaner ..> WeatherExtractor : cleans
DataValidator ..> DataCleaner : validates
FeatureEngineer ..> DataCleaner : enriches
RiskCalculator ..> FeatureEngineer : calculates risk
DatabaseLoader *-- Database : uses

@enduml
